version: "3.7"
services:

  eureka-serviceregistry:
    image: eureka-serviceregistry
    container_name: eureka-serviceregistry
    build: ./eureka
    tty: true
    networks:
      - demo
    ports:
      - "8761:8761"
#  eureka-serviceregistry:
#    build: ./eureka
#    ports:
#      - "8761:8761"
#    tty: true

  mysql_db:
    image: mysql:latest
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rentAcar
    volumes:
      - mysql_db_container:/var/lib/mysql

  xml-service-messages:
    image: xml-service-messages
    container_name: xml-service-messages
    build: ./xml-service-messages
#      context: ./xml-service-messages
#      dockerfile: Dockerfile
    tty: true
    restart: on-failure
#    networks:
#      - demo
    ports:
      - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - MYSQL_HOST=mysql_db
#    environment:
#      REGISTRY_HOST: eureka-serviceregistry
#      MYSQL_HOST: mysql_db
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
#      DATABASE_USERNAME: root
#      DATABASE_PASSWORD: root
#      DATABASE_DOMAIN: mysql_db
#      DATABASE_SCHEMA: message_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
        - eureka-serviceregistry
        - mysql_db

#  xml-service-oglas:
#    image: xml-service-oglas
#    container_name: xml-service-oglas
#    build:
#      context: ./xml-service-oglas
#      dockerfile: Dockerfile
#    tty: true
#    restart: on-failure
#    networks:
#      - demo
#    ports:
#      - "8086:8086"
#    environment:
#      #REGISTRY_HOST: eureka-serviceregistry
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
#      DATABASE_USERNAME: root
#      DATABASE_PASSWORD: root
#      DATABASE_DOMAIN: mysql
#      DATABASE_SCHEMA: ad_db?createDatabaseIfNotExist=true&serverTimezone=UTC
#    depends_on:
#      - eureka-serviceregistry
#      - mysql

#  xml-service-pretraga:
#    image: xml-service-pretraga
#    container_name: xml-service-pretraga
#    build:
#      context: ./xml-service-pretraga
#      dockerfile: Dockerfile
#    tty: true
#    restart: on-failure
#    networks:
#      - demo
#    ports:
#      - "8087:8087"
#    environment:
#      #REGISTRY_HOST: eureka-serviceregistry
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
#      DATABASE_USERNAME: root
#      DATABASE_PASSWORD: root
#      DATABASE_DOMAIN: mysql
#      DATABASE_SCHEMA: search_db?createDatabaseIfNotExist=true&serverTimezone=UTC
#    depends_on:
#      - eureka-serviceregistry
#      - mysql

#  xml-service-user:
#    image: xml-service-user
#    container_name: xml-service-user
#    build:
#      context: ./xml-service-user
#      dockerfile: Dockerfile
#    tty: true
#    restart: on-failure
#    networks:
#      - demo
#    ports:
#      - "8084:8084"
#    environment:
#      #REGISTRY_HOST: eureka-serviceregistry
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
#      DATABASE_USERNAME: root
#      DATABASE_PASSWORD: root
#      DATABASE_DOMAIN: mysql
#      DATABASE_SCHEMA: user_db?createDatabaseIfNotExist=true&serverTimezone=UTC
#    depends_on:
#      - eureka-serviceregistry
#      - mysql

#  xml-service-vozilo:
#    image: xml-service-vozilo
#    container_name: xml-service-vozilo
#    build:
#      context: ./xml-service-vozilo
#      dockerfile: Dockerfile
#    tty: true
#    restart: on-failure
#    networks:
#      - demo
#    ports:
#      - "8088:8088"
#    environment:
#      #REGISTRY_HOST: eureka-serviceregistry
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
#      DATABASE_USERNAME: root
#      DATABASE_PASSWORD: root
#      DATABASE_DOMAIN: mysql
#      DATABASE_SCHEMA: vehicle_db?createDatabaseIfNotExist=true&serverTimezone=UTC
#    depends_on:
#      - eureka-serviceregistry
#      - mysql


  zuul:
    image: zuul
    container_name: zuul
    build:
      context: ./zuul
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    tty: true
    networks:
      - demo
    ports:
      - "8083:8083"
    depends_on:
      - eureka-serviceregistry
      - xml-service-messages
#      - xml-service-oglas
#      - xml-service-pretraga
#      - xml-service-user
#      - xml-service-vozilo


#  xml-service:
#    image: xml-service
#    container_name: xml-service
#    build: ./xml-service
#    #context: ./xml-service
#    #dockerfile: Dockerfile
#    tty: true
#    restart: on-failure
#    networks:
#      - demo
#    ports:
#      - "8089:8089"
#    environment:
#
#      # REGISTRY_HOST=eureka-serviceregistry
#      - MYSQL_HOST=mysql_db
#    depends_on:
#      - mysql_db


volumes:
  mysql_db_container:

networks:
  demo:
    name: demo
    driver: bridge

