version: "3.7"

services:
  eureka-serviceregistry:
    image: eureka-serviceregistry
    container_name: eureka-serviceregistry
    build: ./eureka
    tty: true
    networks:
      - demo
    ports:
      - "8761:8761"


  xml-service-messages:
    image: xml-service-messages
    container_name: xml-service-messages
    build:
      context: ./xml-service-messages
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8085:8085"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: message_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql

  xml-service-oglas:
    image: xml-service-oglas
    container_name: xml-service-oglas
    build: ./xml-service-oglas
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8086:8086"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: ad_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql

  xml-service-pretraga:
    image: xml-service-pretraga
    container_name: xml-service-pretraga
    build: ./xml-service-pretraga
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8087:8087"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: search_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql

  xml-service-user:
    image: xml-service-user
    container_name: xml-service-user
    build: ./xml-service-user
#      context: ./xml-service-user
#      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8084:8084"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: user_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql
#
  xml-service-vozilo:
    image: xml-service-vozilo
    container_name: xml-service-vozilo
    build: ./xml-service-vozilo
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8088:8088"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: vehicle_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql


  zuul:
    image: zuul
    container_name: zuul
    build: ./zuul
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    tty: true
    networks:
      - demo
    ports:
      - "8083:8083"
    depends_on:
      - eureka-serviceregistry
      - xml-service-messages
      - xml-service-oglas
      - xml-service-pretraga
      - xml-service-user
      - xml-service-vozilo


  xml-service:
    image: xml-service
    container_name: xml-service
    build: ./xml-service
    #context: ./xml-service
    #dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8089:8089"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: rentAcar?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root


networks:
  demo:
    name: demo
    driver: bridge

